services:
  codx-junior:
    container_name: codx-junior
    image: lscr.io/linuxserver/webtop:debian-kde
    shm_size: 2gb
    volumes:
      - ./docker-init:/custom-cont-init.d:ro
      - ./code-server/extensions:/root/.local/share/code-server/extensions
      - ./code-server/User:/root/.local/share/code-server/User
      - .:/config/codx-junior
    ports:
      - 8080:9983 #Web
      - 8081:9080 #coder
