services:

  codx-junior-all:
    image: codx-junior:latest
    build: 
      context: .
      # User permissions
      args:
        - USER_GID=${USER_GID:-1001}
        - USER_UID=${USER_UID:-1001}
    container_name: codx-junior-all
    shm_size: 4gb
    privileged: true
    environment:
      # ALL IN ONE
      - CODX_JUNIOR_APPS=api client llm-factory docker
      # SETTINGS FILE
      - CODX_JUNIOR_GLOBAL_SETTINGS_PATH=/home/codx-junior/.codx-junior-settings.json
      # LLM Settings (Use any OpenAI compatible)
      - CODX_JUNIOR_LLMFACTORY_API=https://api.openai.com/v1
      - CODX_JUNIOR_LLMFACTORY_KEY=sk-********
      - CODX_JUNIOR_LLMFACTORY_KNOWLEDGE_MODEL=gpt-4o
      - CODX_JUNIOR_LLMFACTORY_EMBEDDINGS_MODEL=text-embedding-3-small
    volumes:
      - .:/home/codx-junior/codx-junior
    ports:
      # CODX_JUNIOR_WEB_PORT
      - 8080:19981
    networks:
      - codx-junior

networks:
  codx-junior:
