services:
  codx-junior:
    container_name: codx-junior
    image: codx-junior:latest
    build: .
    env_file:
      - .env.dev
    environment:
      - DEBUG=1
      # HOST_USER to fix permissions from files generated
      - HOST_USER
    volumes:
      - $PWD:/projects/codx-junior
      - "${HOST_PROJECTS_ROOT_PATH}:${HOST_PROJECTS_ROOT_PATH}"
    network_mode: host
