FROM debian:latest AS api

ENV CODX_JUNIOR_PATH=/usr/local/codx-junior
# API virtual env
ENV CODX_JUNIOR_API_VENV=/tmp/.venv_codx_junior_api

RUN apt-get update && \
    apt-get install -y python3 python3-venv nano && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY api ${CODX_JUNIOR_PATH}/api
COPY scripts ${CODX_JUNIOR_PATH}/scripts

RUN chmod +x ${CODX_JUNIOR_PATH}/scripts/install_api.sh
RUN bash ${CODX_JUNIOR_PATH}/scripts/install_api.sh

