FROM codx-junior:latest

RUN apt update && apt install -y fuse-overlayfs &&\
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN codx docker

COPY supervisor.dind.conf /etc/supervisord/docker.conf