services:
  codx-junior:
    image: codx-junior:dev
    build: .
    env_file:
      - .env.dev
    volumes:
      - "${HOST_PROJECTS_ROOT_PATH}:${HOST_PROJECTS_ROOT_PATH}"
    command: bash "run_api.sh"

    