services:
  codx-junior:
    container_name: codx-junior
    image: codx-junior:latest
    build: .
    env_file:
      - .env.dev
    environment:
      - DEBUG=1
    volumes:
      - $PWD:/projects/codx-junior
      - "${HOST_PROJECTS_ROOT_PATH}:${HOST_PROJECTS_ROOT_PATH}"
    ports:
      - "9999:9080"
      - "8083:8083"
