services:

  codx-junior-build:
    env_file:
      - .env
    container_name: codx-junior-build
    image: codx-junior:latest
    build: 
      context: .
      args:
        - CODX_JUNIOR_BRANCH=v1.0-hello-codx-junior
        - USER_GID=1001
        - USER_UID=1001
  
  codx-junior:
    depends_on:
      - codx-junior-build
    container_name: codx-junior
    image: codx-junior:latest
    shm_size: 4gb
    privileged: true
    restart: unless_stopped
    volumes:
      - .:/home/codx-junior/codx-junior
    ports:
      - 19980:19980 # CODX_JUNIOR_API_PORT
      - 19981:19981 # CODX_JUNIOR_WEB_PORT
      - 19982:19982 # CODX_JUNIOR_CODER_PORT
      - 19983:19983 # CODX_JUNIOR_NOVNC_PORT

