# CODX CLIENT PROCESSES
[program:codx-junior-web]
environment=HOME="/home/codx-junior",
            USER="codx-junior",
            DEBUG="%(ENV_DEBUG)s",
            CODX_JUNIOR_API_URL="%(ENV_CODX_JUNIOR_API_URL)s",
            CODX_JUNIOR_HOME="%(ENV_CODX_JUNIOR_PATH)s",
            CODX_JUNIOR_API_PORT="%(ENV_CODX_JUNIOR_API_PORT)s",
            WEB_PORT="%(ENV_CODX_JUNIOR_WEB_PORT)s"
autorestart=true
priority=300
user=codx-junior
redirect_stderr=true
directory=%(ENV_CODX_JUNIOR_PATH)s
command=bash %(ENV_CODX_JUNIOR_PATH)s/scripts/run_client.sh
stdout_logfile=%(ENV_CODX_SUPERVISOR_LOG_FOLDER)s/codx-junior-web.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=7
