{
  "name": "devops",
  "url": "",
  "avatar": "https://api.dicebear.com/10.x/icons/svg?seed=devops",
  "description": "DevOps engineer profile. It will participate in any action related to infrastructure, containerization, CI/CD, IaC, monitoring, and DevOps operations.",
  "category": "project",
  "file_match": "",
  "content": null,
  "parsed_content": null,
  "path": "/home/codx-junior-projects/codx-junior/.codx/profiles/devops/devops.profile",
  "profiles": [],
  "llm_model": "",
  "use_knowledge": true,
  "user": {
    "username": "",
    "email": "",
    "avatar": "",
    "theme": "dim",
    "projects": [],
    "role": "user",
    "token": "",
    "disabled": false,
    "github": "",
    "apps": [],
    "api_key": "",
    "env": {},
    "wallet": {
      "wallet_id": "f781d36e-65d6-4106-9a4c-609e3b16787c",
      "name": "Default Wallet",
      "balance_cxjcoins": 0.0,
      "spending_limits": [],
      "transactions": [],
      "created_at": "2026-08-13T10:12:51.310151",
      "updated_at": "2026-08-13T10:12:51.310161",
      "enabled": true
    },
    "github_admin": false,
    "github_only": false,
    "token_limit_rules": [],
    "token_limit_requests": []
  },
  "tools": [
    "project_search",
    "project_read_file",
    "project_structure",
    "generate_tasks_tool",
    "create_task",
    "docker_container",
    "docker_compose_service",
    "docker_ps"
  ],
  "tags": [],
  "api_settings": {
    "active": false,
    "model_name": null,
    "description": null
  },
  "chat_mode": null,
  "project_id": "d4e4b4a9-2281-4970-bff1-f845b4d98456",
  "chat_id": "82074be7-909e-4ba5-9ade-594a122d21e8"
}