board: kanban
branch: ''
chat_index: 0
chat_links: []
check_lists: []
child_index: 0
column: tasks
column_id: ''
created_at: '2025-12-07 13:27:59.584350'
description: ''
doc_id: null
file_list: []
file_path: /home/codx-junior/codx-junior/.codx/tasks/kanban/tasks/.44111e8b-0b45-4ac1-9512-472af462c23e.yaml
id: 44111e8b-0b45-4ac1-9512-472af462c23e
kanban_id: ''
knowledge_topics: []
llm_model: ''
message_id: null
messages: []
mode: chat
name: ''
parent_id: null
parent_project_id: null
pinned: false
pr_view: {}
profiles: []
project_id: null
remote_url: ''
status: ''
tags: []
target_project_id: null
updated_at: '2025-12-07T13:30:05.065772'
url: ''
users: []
visibility: ''
