board: Docker
branch: ''
chat_index: 0
chat_links: []
check_lists: []
column: Images
column_id: ''
created_at: '2025-10-04 07:53:47.314235'
description: ''
doc_id: null
file_list: []
file_path: /shared/codx-junior/api/.codx/tasks/Docker/Images/codx-junior-dind.f42d703a-fee3-4d44-a73a-b94ff7aca226.yaml
id: f42d703a-fee3-4d44-a73a-b94ff7aca226
kanban_id: ''
knowledge_topics: []
llm_model: ''
message_id: null
messages: []
mode: task
name: codx-junior:dind
parent_id: null
pinned: false
pr_view: {}
profiles: []
project_id: null
remote_url: ''
status: ''
tags: []
updated_at: '2025-10-04T07:54:42.266115'
url: ''
users: []
visibility: ''
