services:
  llm-factory:
    image: python:3.10-slim
    container_name: llm-factory
    working_dir: /app
    volumes:
      - ./:/app
    command: bash run-factory.sh
    environment:
      - PYTHONUNBUFFERED=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.llm-factory.rule=PathPrefix(`/admin`)"
      - "traefik.http.services.llm-factory.loadbalancer.server.port=8000"
    networks:
      - web

  ollama:
    image: ollama/ollama
    container_name: ollama
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama.rule=(PathPrefix(`/api`) || PathPrefix(`/v1`))"
      - "traefik.http.services.ollama.loadbalancer.server.port=11434"
    volumes:
      - ./ollama-data:/root/.ollama
    networks:
      - web

  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
      - "--accesslog=true"
    ports:
      - "8754:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

networks:
  web:
    driver: bridge
