"""
knowledge_ai_search_message.py

Helper utility for converting an :class:`AISearchResult` into a fully-populated
:class:`~codx.junior.db.Message` that can be appended to a chat.

The produced message always carries:
  - ``task_item = TASK_ITEM_SEARCH``  — signals to consumers that this
    message was generated by the AI search pipeline.
  - ``content``  — the AI-generated prose answer.
  - ``files``    — deduplicated list of source paths that contributed to
    the answer.

Usage example::

    from codx.junior.knowledge.knowledge_ai_search_message import (
        build_search_message,
    )

    msg = build_search_message(ai_search_result)
    chat.messages.append(msg)

Diagram:
flowchart TD
    A[AISearchResult] --> B[Extract answer → message.content]
    A --> C[Extract document sources → deduplicate → message.files]
    B --> D[Build Message with task_item=TASK_ITEM_SEARCH]
    C --> D
    D --> E[Return Message]
"""

import logging
import uuid
from datetime import datetime
from typing import List

from codx.junior.db import Message
from codx.junior.knowledge.knowledge_ai_search import AISearchResult

logger = logging.getLogger(__name__)

# Task item identifier that marks a message as produced by the AI search pipeline.
TASK_ITEM_SEARCH = "search"


def build_search_message(result: AISearchResult) -> Message:
    """
    Convert an :class:`AISearchResult` into a chat :class:`Message`.

    The message is given ``task_item = TASK_ITEM_SEARCH`` so downstream
    consumers (UI, indexers, chat engines) can identify it as a search
    result rather than a normal assistant turn.

    Distinct source paths are extracted from each document's metadata and
    stored in ``message.files``.  Documents that share a source path
    (different chunks of the same file) are collapsed to a single entry so
    the file list remains clean.

    Diagram:
    flowchart TD
        A[AISearchResult] --> B[answer → content]
        A --> C[documents metadata source]
        C --> D[Deduplicate sources preserving insertion order]
        D --> E[files list]
        B --> F[Assemble Message]
        E --> F
        F --> G[Return Message]

    Args:
        result: The :class:`AISearchResult` returned by
                :py:meth:`KnowledgeAISearch.ai_search`.

    Returns:
        A :class:`~codx.junior.db.Message` with:
          - ``role``      = ``"assistant"``
          - ``task_item`` = :data:`TASK_ITEM_SEARCH`
          - ``content``   = AI-generated answer prose
          - ``files``     = ordered, deduplicated list of source paths
    """
    # Collect distinct source paths while preserving insertion order.
    seen_sources: set = set()
    distinct_sources: List[str] = []
    for doc in result.documents:
        source: str = doc.metadata.get("source", "")
        if source and source not in seen_sources:
            seen_sources.add(source)
            distinct_sources.append(source)

    logger.info(
        "build_search_message: query=%r | answer_len=%d | "
        "documents=%d | distinct_sources=%d",
        result.user_query,
        len(result.answer),
        len(result.documents),
        len(distinct_sources),
    )

    message = Message(
        doc_id=str(uuid.uuid4()),
        role="assistant",
        task_item=TASK_ITEM_SEARCH,
        content=result.answer,
        files=distinct_sources,
        created_at=str(datetime.now()),
        updated_at=str(datetime.now()),
        meta_data={
            "user_query": result.user_query,
            "total_iterations": result.total_iterations,
            "queries_used": result.queries_used,
            "projects_searched": result.projects_searched,
        },
    )

    logger.debug(
        "build_search_message: created message doc_id=%s with %d source files.",
        message.doc_id,
        len(distinct_sources),
    )

    return message

# Made with ❤️ by codx-junior
