LANGUAGE_FROM_EXTENSION = {
    "py": "python",
    "java": "java",
    "js": "js",
    "cpp": "cpp",
    "go": "go",
    "rb": "ruby",
    "php": "php",
    "swift": "swift",
    "kt": "kotlin",
    "rs": "rust",
    "sh": "shell",
    "r": "r",
    "pl": "perl",
    "scala": "scala",
    "ts": "ts",
    "md": "markdown",
    "txt": "text",
    "html": "html",
    "cs": "csharp",
    "cshtml": "html",
    "json": "js",
}

CODE_PARSER_FROM_EXTENSION = {
    "py": "python",
    "java": "java",
    "js": "js",
    "cpp": "cpp",
    "go": "go",
    "rb": "ruby",
    "php": "php",
    "swift": "swift",
    "kt": "kotlin",
    "rs": "rust",
    "sh": "shell",
    "r": "r",
    "pl": "perl",
    "scala": "scala",
    "ts": "typescript",
    "md": "markdown",
    "txt": "text",
    "html": "html",
    "cs": "csharp",
    "cshtml": "html",
    "json": "js",
}