board: kanban
branch: ''
chat_index: 0
chat_links: []
check_lists: []
child_index: 0
column: tasks
column_id: ''
created_at: '2025-12-07 06:45:51.725313'
description: ''
doc_id: null
file_list: []
file_path: /home/codx-junior/codx-junior/client/.codx/tasks/kanban/tasks/.b90e6b0a-75d0-42c6-81a8-edcabbbb0e24.yaml
id: b90e6b0a-75d0-42c6-81a8-edcabbbb0e24
kanban_id: ''
knowledge_topics: []
llm_model: ''
message_id: null
messages: []
mode: chat
name: ''
parent_id: null
parent_project_id: null
pinned: false
pr_view: {}
profiles: []
project_id: null
remote_url: ''
status: ''
tags: []
target_project_id: null
updated_at: '2025-12-07T07:54:46.190418'
url: ''
users: []
visibility: ''
