##################################################
## codx-junior:debian
##################################################
FROM debian:12 as common

ENV DEBIAN_FRONTEND=noninteractive
ENV CODX_JUNIOR_API_VENV=/tmp/.venv_codx_junior_api

# TODO: Review this 
RUN apt update && apt install -y \
    curl sudo locales git \
    wget nano \
    locales python3.11 python3.11-venv \
    procps git \
    texlive-xetex texlive-fonts-recommended

# TODO: Clean after

RUN echo "LC_ALL=en_US.UTF-8" >> /etc/environment
RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
RUN echo "LANG=en_US.UTF-8" > /etc/locale.conf
RUN locale-gen en_US.UTF-8

ARG USER_UID=1001
ARG USER_GID=1001
ENV USER="codx-junior"
ENV HOME="/home/${USER}"

# Create user with specified UID and GID
RUN groupadd -g ${USER_GID} codx-junior
RUN useradd -u ${USER_UID} -g ${USER_GID} -s /bin/bash -m -d ${HOME} $USER

# Add user to sudoers with no password
RUN echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER ${USER}
WORKDIR ${HOME}/codx-junior

COPY --chown=${USER} scripts ./scripts
COPY --chown=${USER} set_env.sh .

ENV CODX_JUNIOR_PATH=${HOME}/codx-junior

RUN bash scripts/install_base.sh

# Install codx-cli
RUN curl -sL "https://raw.githubusercontent.com/gbrian/codx-cli/main/codx.sh" | bash -s



