FROM localai/localai:latest

# Install Hugging Face CLI
RUN apt update && apt install -y python3 python3-pip curl
RUN apt install -y python3.12-venv
RUN curl -LsSf https://hf.co/cli/install.sh | bash
